version: '3.8'

# SYNTAX: docker compose up --detach

services:
  credential-service:
    build: .
    depends_on:
      - database
    image: credential-service:latest
    ports:
      - 8787:8787
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: "npm run compose-run"

  database:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
    
