# Worker name
name = "credential-service"

# Entrypoint/path to the file that will be executed
main = "./src/index.ts"

[vars]
NETWORK_RPC_URL = "https://rpc.cheqd.net"

# Configuration options for local development via Wrangler
[dev]
	# IP address for the local dev server to listen on
	# @default `localhost`
	ip = "localhost"
	# Port for the local dev server to listen on
	# @default `8787`
	port = 8787
	# Protocol that local wrangler dev server listens to requests on
	# @default `http`
	local_protocol = "http"

[env.staging]
# Worker name - Staging Environment
name = "credential-service-staging"
