name = "credentials-auth"
main = "src/index.ts"
account_id = "99b9572de9d3c33774965949416b82c9"
workers_dev = true
compatibility_date = "2022-04-14"

node_compat = true

kv_namespaces = [
	{ binding = "CREDENTIALS", preview_id = "08f012b41df44fd3b6849100d02b7cba", id = "08f012b41df44fd3b6849100d02b7cba" }
]

[vars]
_ISSUER_ID = "did:cheqd:mainnet:z6fVEeX9YpnABifLvPTsgYmS4o5QGM77"

_ISSUER_ID_PRIVATE_KEY_HEX = "0019f40cdd2b9ee6807d9d6fb66cb775e95d6e1dac039bb2a93a9a08263a9fe28da6bbd0af72cb84f0f9812c0364f8175d23b10b8576954937d2cb86398e506c"

_ISSUER_ID_PUBLIC_KEY_HEX = "8da6bbd0af72cb84f0f9812c0364f8175d23b10b8576954937d2cb86398e506c"

_ISSUER_ID_KID = "jaa70K9yy4Tw-YEsA2T4F10jsQuFdpVJN9LLhjmOUGw"

_ISSUER_ID_METHOD_SPECIFIC_ID = "zAXwwqZzhCZA1L77ZBa8fhVNjL9MQCHX"

_ISSUER_ID_METHOD = "did:cheqd:mainnet:"

_TWITTER_CONSUMER_KEY = "ZVE0QzhiMWY1R0E2WmVTUm5JQko6MTpjaQ"

_TWITTER_CONSUMER_SECRET = "WLQoQYifP8nUsgv9zjML0Affkf12NRLr24FqRg8sjpALVxpm31"

_TWITTER_STATE_CSRF = "z6MkoyogvBv1G8acpsxWpbg75a2hMALabPMPxXhniMQyJBq3"

[miniflare]
env_path=".env"
