version: '3.8'

# CAUTION: Please ensure you edit necessary values in .env before using this Docker Compose file.

# SYNTAX: docker compose -f docker/docker-compose.yml up --detach

services:
  app:
    image: ghcr.io/cheqd/credential-service:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3000:3000
    env_file:
      - .env.with-db

  app-migrations:
    image: ghcr.io/cheqd/credential-service:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3000:3000
    env_file:
      - .env.with-db
    entrypoint: [ "npm", "run", "migrate", "&&", "npm", "run", "seed" ]
    profiles:
      - setup

  logto:
    image: ghcr.io/cheqd/creds-auth:latest
    ports:
      - 3001:3001
      - 3002:3002
    env_file:
      - .env
    profiles:
      - logto

  logto-migrations:
    image: ghcr.io/cheqd/creds-auth:latest
    ports:
      - 3001:3001
      - 3002:3002
    env_file:
      - .env
    entrypoint: [ "npm", "run", "migrate", "&&", "npm", "run", "seed" ]
    profiles:
      - setup
      - logto

  postgres:
    image: postgres
    user: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - external-kms
      - logto
