version: '3.8'

# CAUTION: Please ensure you edit necessary values in no-db.env before using this Docker Compose file.

# SYNTAX: docker compose -f docker/no-external-db/docker-compose-no-db.yml up --detach

services:
    app:
        # To change the image version, edit the ":latest" tag to the desired version
        # For production/stable release, use ":latest"
        # For development/staging release, use ":staging-latest"
        image: ghcr.io/cheqd/studio:latest
        ports:
            - 3000:3000
        # NOTE: Edit the values present within this file before running the service
        env_file:
            - no-db.env
