version: '3.8'

# CAUTION: Please ensure you edit necessary values in with-db.env before using this Docker Compose file.

# SYNTAX: docker compose -f docker/with-external-db/docker-compose-with-db.yml up --detach

services:
  app:
    image: ghcr.io/cheqd/credential-service:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3000:3000
    env_file:
      - with-db.env
    profiles:
      - app-without-external-db

  app-migrations:
    image: ghcr.io/cheqd/credential-service:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3000:3000
    env_file:
      - with-db.env
    entrypoint: [ "sh", "-c", "npm run migration && npm run start" ]
    profiles:
      - app-with-external-db

  logto:
    image: ghcr.io/logto-io/logto:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3001:3001
      - 3002:3002
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    env_file:
      - .env
    profiles:
      - logto

  postgres:
    image: postgres
    user: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - external-kms
      - logto
