version: '3.8'

# CAUTION: Please ensure you edit necessary values in with-db.env before using this Docker Compose file.

# SYNTAX: docker compose -f docker/with-external-db/docker-compose-with-db.yml up --detach

services:
  app:
    # To change the image version, edit the ":latest" tag to the desired version
    # For production/stable release, use ":latest"
    # For development/staging release, use ":staging-latest"
    image: ghcr.io/cheqd/credential-service:latest
    depends_on:
      postgres:
        condition: service_healthy
      app-migrations:
        condition: service_started
      logto:
        condition: service_started
    ports:
      - 3000:3000
    env_file:
      - with-db.env
    profiles:
      - app

  # This service is used as a ONE-TIME setup service to run migrations
  # Only relevant if you're using the app with EXTERNAL_DB=true
  app-migrations:
    image: ghcr.io/cheqd/credential-service:latest
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - with-db.env
    entrypoint: [ "npm", "run", "migration" ]
    profiles:
      - app-setup
      - external-kms
      - app

  # This service is used to run a PostgreSQL database
  # Used in the following scenarios:
  # 1. When you're using the app with EXTERNAL_DB=true
  # 2. When you're using the app with LogTo enabled using ENABLE_AUTHENTICATION=true
  postgres:
    image: postgres:15-alpine
    user: postgres
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    # Edit the environment variables in postgres.env to change the database name, username, password, etc.
    # Postgres setup and configuration is outside the scope of this file.
    env_file:
      - postgres.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - external-kms
      - logto
      - app

  # This service is used to run a LogTo instance for authentication
  # Used when ENABLE_AUTHENTICATION=true
  logto:
    image: ghcr.io/cheqd/connector-telegram:latest
    depends_on:
      postgres:
        condition: service_healthy
      logto-migrations:
        condition: service_started
    ports:
      - 3001:3001
      - 3002:3002
    env_file:
      - logto.env
    profiles:
      - logto
      - app

  # This service is used as a ONE-TIME setup service to run migrations for LogTo
  # Only relevant if you're using the app with EXTERNAL_AUTHENTICATION=true
  logto-migrations:
    image: ghcr.io/cheqd/connector-telegram:latest
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["bash", "/etc/logto/entrypoint.sh", "--alter-db", "1.3.0"]
    env_file:
      - logto.env
    profiles:
      - logto
      - logto-setup
      - app
