name = "credentials-back-end"
type = "javascript"
zone_id = "afe3b66243382f27140e6feeaae848b5"
account_id = "99b9572de9d3c33774965949416b82c9"
route = ""
workers_dev = true
compatibility_date = "2022-04-14"

kv_namespaces = [
	 { binding = "CREDENTIALS", preview_id = "08f012b41df44fd3b6849100d02b7cba" }
]

[build]
command = "true"
[build.upload]
format = "service-worker"

[miniflare]
env_path=".env"
