name: "Build"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  build:
    name: "Build Node.js"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          # cache: 'npm' <--- Commenting out, see: https://github.com/bahmutov/npm-install/issues/80, as of 13th of June 2022.
          # cache-dependency-path: '**/package-lock.json' <--- Commenting out, see: https://github.com/bahmutov/npm-install/issues/80, as of 13th of June 2022.

      - name: "Clean install dependencies"
        run: npm install
        env:
          NPM_GITHUB_PAT: ${{ secrets.NPM_GITHUB_PAT }}

      - name: "Run npm build"
        run: npm run build
