name: "Build"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  build:
    name: "Build Node.js"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: registry.digitalocean.com/${{ github.repository }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
          version: latest
      
      - name: Configure Docker image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.ref_name }}
            type=raw,value=staging-latest
            type=sha,format=long
          labels: |
            org.opencontainers.image.description="Cheqd Credential Service"
            org.opencontainers.image.source="https://github.com/cheqd/credential-service"
            org.opencontainers.image.vendor="Cheqd Foundation Limited"
            org.opencontainers.image.created={{date 'dddd, MMMM Do YYYY, h:mm:ss a'}}
            org.opencontainers.image.documentation="https://docs.cheqd.io/node"

      - name: Configure Docker image metadata
        id: build-meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=staging-latest
            type=ref,event=branch
            type=sha,format=long

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          load: true
          tags: ${{ steps.build-meta.outputs.tags }}
      
      - name: Save docker image
        run:  docker save ${{ env.IMAGE_NAME }} > /tmp/credential-service-image.tar

      - name: Upload build image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: credential-service-image
          path: /tmp/credential-service-image.tar
