name: 'Build'
on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [ 'auth', credentials ]
        node: [ 14, 16 ]
    name: Build Node v${{ matrix.node }} - ${{ matrix.dir }}:service
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Local Build - did-provider-cheqd
        working-directory: credentials/did-provider-cheqd
        run: |
          npm install

      - name: Local Build - cheqd-credential-issuer
        working-directory: credentials/cheqd-credential-issuer
        run: |
          npm install

      - name: NPM build
        working-directory: ${{ matrix.dir }}
        run: |
          npm install
          npm run build
