name: "Push staging container image to DOCR"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  push-staging-image:
    name: "Push staging docker image to DOCR"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: registry.digitalocean.com/${{ github.repository }}
    environment: 
      name: staging

    steps:
      - name: Install DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login --expiry-seconds 600

      - name: Download docker image
        uses: actions/download-artifact@v3
        with:
          name: credential-service-image
          path: /tmp

      - name: Load docker images
        run: docker image load --input /tmp/credential-service-image.tar

      - name: Push images to DOCR
        run: docker image push --all-tags ${{ env.IMAGE_NAME }}
