name: "Deploy"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  deploy-staging:
    name: "Staging Deploy"
    runs-on: ubuntu-latest
    continue-on-error: true
    env: 
      IMAGE_NAME: registry.digitalocean.com/${{ github.repository }}
    environment: 
      name: staging

    steps:
      - name: Install DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login --expiry-seconds 600

      - name: Download docker image
        uses: actions/download-artifact@v3
        with:
          name: credential-service-staging

      - name: Load Docker image
        run: docker image load --input credential-service-staging.tar

      - name: Push images to DOCR
        run: docker image push --all-tags ${{ env.IMAGE_NAME }}
