name: Playwright Tests
on:
  workflow_call:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: Playwright
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Build and start the server
      run: npm run build && npm run start

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test -c playwright.config.ts

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
