name: 'Build'
on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [ 'credentials-back-end' ]
        node: [ 12, 14, 16 ]
    name: Test Node v${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Local Build - did-provider-cheqd
        working-directory: ${{ matrix.dir }}/did-provider-cheqd
        run: |
          npm install

      - name: Local Build - cheqd-credential-issuer
        working-directory: ${{ matrix.dir }}/cheqd-credential-issuer
        run: |
          npm install

      - name: NPM test
        working-directory: ${{ matrix.dir }}
        run: |
          npm install
          npm run build
          npm run generate-plugin-schema
          npm run test
