name: Playwright Tests
on:
  workflow_call:
env:
  COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
  EXTERNAL_DB_CERT: ${{ secrets.EXTERNAL_DB_CERT }}
  EXTERNAL_DB_CONNECTION_URL: ${{ secrets.EXTERNAL_DB_CONNECTION_URL }}
  EXTERNAL_DB_ENCRYPTION_KEY: ${{ secrets.EXTERNAL_DB_ENCRYPTION_KEY }}
  LOGTO_APP_SECRET: ${{ secrets.LOGTO_APP_SECRET }}
  LOGTO_M2M_APP_SECRET: ${{ secrets.LOGTO_M2M_APP_SECRET }}
  LOGTO_WEBHOOK_SECRET: ${{ secrets.LOGTO_WEBHOOK_SECRET }}
  POLYGON_PRIVATE_KEY: ${{ secrets.POLYGON_PRIVATE_KEY }}
  VERIDA_PRIVATE_KEY: ${{ secrets.VERIDA_PRIVATE_KEY }}
  TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
  TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

  APPLICATION_BASE_URL: ${{ vars.APPLICATION_BASE_URL }}
  ENABLE_AUTHENTICATION: ${{ vars.ENABLE_AUTHENTICATION }}
  ENABLE_EXTERNAL_DB: ${{ vars.ENABLE_EXTERNAL_DB }}
  ENABLE_VERIDA_CONNECTOR: ${{ vars.ENABLE_VERIDA_CONNECTOR }}
  LOGTO_APP_ID: ${{ vars.LOGTO_APP_ID }}
  LOGTO_DEFAULT_RESOURCE_URL: ${{ vars.LOGTO_DEFAULT_RESOURCE_URL }}
  LOGTO_DEFAULT_ROLE_ID: ${{ vars.LOGTO_DEFAULT_ROLE_ID }}
  LOGTO_ENDPOINT: ${{ vars.LOGTO_ENDPOINT }}
  LOGTO_M2M_APP_ID: ${{ vars.LOGTO_M2M_APP_ID }}
  LOGTO_MANAGEMENT_API: ${{ vars.LOGTO_MANAGEMENT_API }}
  MAINNET_RPC_URL: ${{ vars.MAINNET_RPC_URL }}
  RESOLVER_URL: ${{ vars.RESOLVER_URL }}
  TESTNET_RPC_URL: ${{ vars.TESTNET_RPC_URL }}
  VERIDA_NETWORK: ${{ vars.VERIDA_NETWORK }}
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: Playwright
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci

    - name: Build and start the server
      run: npm run build && npm run start

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test -c playwright.config.ts

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
