name: 'Build'
on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [ 'credentials-back-end' ]
        node: [ 12, 14, 16 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm cache dir)"
      
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}

      - name: NPM test
        working-directory: ${{ matrix.node }}
        run: |
          npm install
          npm run build
          npm run generate-plugin-schema
          npm run test
